# Generated by Django 5.0 on 2024-01-02 01:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Puesto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre",
                    models.CharField(max_length=32, verbose_name="Nombre del puesto"),
                ),
                (
                    "descripcion",
                    models.TextField(
                        blank=True,
                        max_length=512,
                        verbose_name="Descripcción (Máximo 512 caracterés)",
                    ),
                ),
            ],
            options={
                "verbose_name": "Puesto",
                "verbose_name_plural": "Listado de puestos",
            },
        ),
        migrations.CreateModel(
            name="TipoObra",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=32, verbose_name="Nombre")),
                (
                    "descripcion",
                    models.CharField(
                        max_length=512, verbose_name="Descripcción detallada"
                    ),
                ),
            ],
            options={
                "verbose_name": "Tipo de obra",
                "verbose_name_plural": "Tipos de obra para usar",
            },
        ),
        migrations.CreateModel(
            name="Material",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=32, verbose_name="Nombre")),
                (
                    "descripcion",
                    models.TextField(
                        blank=True,
                        max_length=512,
                        verbose_name="Descripcción (Máximo 512 caracterés)",
                    ),
                ),
                ("cantidad", models.IntegerField(verbose_name="Cantidad")),
                (
                    "precio_unitario",
                    models.IntegerField(
                        verbose_name="Precio unitario (En caso de ser en gramos ingrese por kilo)"
                    ),
                ),
                (
                    "tipo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="catalogo.tipoobra",
                        verbose_name="¿En que será empleado?",
                    ),
                ),
            ],
            options={
                "verbose_name": "Material",
                "verbose_name_plural": "Listado de materiales",
            },
        ),
        migrations.CreateModel(
            name="Trabajador",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre",
                    models.CharField(max_length=32, verbose_name="Nombre completo"),
                ),
                (
                    "edad",
                    models.IntegerField(verbose_name="Cantidad de años cumplidos"),
                ),
                (
                    "seguridad_social",
                    models.CharField(
                        max_length=32, verbose_name="Número de seguridad social"
                    ),
                ),
                (
                    "puesto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="catalogo.puesto",
                        verbose_name="Puesto del empleado",
                    ),
                ),
            ],
            options={
                "verbose_name": "Trabajador",
                "verbose_name_plural": "Listado de trabajadores",
            },
        ),
    ]
