# Generated by Django 5.0 on 2024-01-07 04:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalogo", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="material",
            name="cantidad",
            field=models.IntegerField(
                validators=[
                    django.core.validators.MinValueValidator(
                        0, message="El valor debe ser igual o mayor a 0."
                    )
                ],
                verbose_name="Cantidad",
            ),
        ),
        migrations.AlterField(
            model_name="material",
            name="precio_unitario",
            field=models.IntegerField(
                validators=[
                    django.core.validators.MinValueValidator(
                        0, message="El valor debe ser igual o mayor a 0."
                    )
                ],
                verbose_name="Precio unitario (En caso de ser en gramos ingrese por kilo)",
            ),
        ),
        migrations.AlterField(
            model_name="trabajador",
            name="edad",
            field=models.IntegerField(
                validators=[
                    django.core.validators.MinValueValidator(
                        18, message="El trabajador no puede ser menor de edad."
                    )
                ],
                verbose_name="Cantidad de años cumplidos",
            ),
        ),
    ]
