# Generated by Django 5.0 on 2024-01-07 04:19

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("e_norte", "0002_alter_general_presupuesto"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="general",
            options={"verbose_name": "General Norte"},
        ),
    ]
